on: 
    push:
        branches:
          - '**'
          - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    test:
      permissions:
        contents: write
        checks: write
        statuses: write
      name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      runs-on: self-hosted
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            lfs: false

        # Cache
        - uses: actions/cache@v3
          with:
            path: Pestis/Library
            key: Pestis/Library
            restore-keys: |
              Pestis/Library-
              Library-Pestis
              Library-

        # Test
        - name: Run tests
          uses: game-ci/unity-test-runner@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            projectPath: Pestis
            runAsHostUser: true
            chownFilesTo: ec2-user

    build-linux:
      needs: test
      permissions:
        contents: write
        checks: write
        statuses: write
      name: Build Linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      runs-on: self-hosted
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            lfs: false

        # Cache
        - uses: actions/cache@v3
          with:
            path: Pestis/Library
            key: Pestis/Library-Linux
            restore-keys: |
              Pestis/Library-
              Library-Pestis
              Library-

        # Build
        - name: Build Linux
          uses: game-ci/unity-builder@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: StandaloneLinux64
            versioning: Custom
            version: ${{ github.ref_name }}
            projectPath: Pestis
            runAsHostUser: true
            chownFilesTo: ec2-user

        # Output
        - name: Zip Linux build to hosting folder
          run: mkdir -p /home/ec2-user/actions-runner/builds/${{ github.ref_name  }}/ && zip -urD /home/ec2-user/actions-runner/builds/${{ github.ref_name  }}/linux.zip build/StandaloneLinux64 

    build-windows:
      needs: test
      permissions:
        contents: write
        checks: write
        statuses: write
      name: Build Windows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      runs-on: self-hosted
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            lfs: false

        # Cache
        - uses: actions/cache@v3
          with:
            path: Pestis/Library
            key: Pestis/Library-Windows
            restore-keys: |
              Pestis/Library-
              Library-Pestis
              Library-
        # Build
        - name: Build Windows
          uses: game-ci/unity-builder@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: StandaloneWindows64
            versioning: Custom
            version: ${{ github.ref_name }}
            projectPath: Pestis
            runAsHostUser: true
            chownFilesTo: ec2-user

        # Output
        - name: Zip Windows build to hosting folder
          run: mkdir -p /home/ec2-user/actions-runner/builds/${{ github.ref_name  }}/ && zip -urD /home/ec2-user/actions-runner/builds/${{ github.ref_name  }}/windows.zip build/StandaloneWindows64 
      
